<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Lesson Information</legend>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="title">Title</label>
  <div class="controls">
    <input id="title" name="title" placeholder="My Lesson" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="subjectarea">Subject Area</label>
  <div class="controls">
    <input id="subjectarea" name="subjectarea" placeholder="Contracts" class="input-xlarge" required="" type="text">
    
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="control-label" for="calidescription">Brief Description</label>
  <div class="controls">                     
    <textarea id="calidescription" name="calidescription"></textarea>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="completiontime">Est. Completion Time</label>
  <div class="controls">
    <input id="completiontime" name="completiontime" placeholder="20 minutes" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="authorname">Author Name</label>
  <div class="controls">
    <input id="authorname" name="authorname" placeholder="Your full name here" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="authortitle">Author title</label>
  <div class="controls">
    <input id="authortitle" name="authortitle" placeholder="Your title" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="authorschool">School</label>
  <div class="controls">
    <input id="authorschool" name="authorschool" placeholder="Your school" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="email">Email</label>
  <div class="controls">
    <input id="email" name="email" placeholder="Your email address" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="phone">Phone</label>
  <div class="controls">
    <input id="phone" name="phone" placeholder="234-456-7890" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="webaddress">Web Site</label>
  <div class="controls">
    <input id="webaddress" name="webaddress" placeholder="http://www.cali.org/" class="input-xlarge" type="text">
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="control-label" for="submit">All done?</label>
  <div class="controls">
    <button id="submit" name="submit" class="btn btn-primary">Next</button>
  </div>
</div>

</fieldset>
</form>