<form class="form-horizontal" method="post">
    <fieldset>
    <legend>Page</legend>
    <!-- Textarea -->
        <div class="form-group">
          <label class="col-sm-2 control-label" for="page">Add text for this page. HTML is allowed.</label>
          <div class="col-sm-8">                     
            <textarea id="page" name="page" class="form-control"></textarea>
          </div>
        </div>

    <!-- Button -->
        <div class="form-group">
          <label class="col-sm-2 control-label" for="page-submit">All done?</label>
          <div class="col-sm-8">
            <button id="page-submit" name="page-submit" class="btn btn-primary">Next</button>
          </div>
        </div>
    </fieldset>
</form>
