<legend>True/False Quiz Question</legend>
 <input type="hidden" name="page-type" value="quiz-tf" />
 <div class="xform-inline">
	 <div class="form-group">
		  <label class="col-sm-2 control-label" for="page">Correct choice?</label>
		  <div class="col-sm-4">
			 <div class="btn-group" data-toggle="buttons">
				 <label class="btn btn-default ">   <input type="radio" name="true-is-correct"  value="true" autocomplete="off"> True   </label>
				 <label class="btn btn-default">    <input type="radio" name="true-is-correct" value="false" autocomplete="off"> False   </label>
			 </div>
		 </div> 
	 </div>
</div>


<script>
cawSetRB('true-is-correct',data['true-is-correct']);
</script>
